"use client";

import { useState } from "react";

interface CitationData {
  resource_id: string;
  title: string;
  page_num: number;
  score: number;
  excerpt: string;
  reason?: string | null;
}

interface Props {
  resourceId: string;
  data?: CitationData;
  /** Override the chip label — e.g. pass the full doc title from the corpus map. */
  label?: string;
  /** If provided, clicking the chip calls this instead of toggling the inline popover. */
  onOpen?: () => void;
}

/** Inline citation chip. Clicking opens a small popover with the source excerpt.
 *
 * The chip renders even if `data` is missing (e.g., the model cited an id that
 * wasn't in the retrieval set — possible if hallucinated). In that case the
 * tooltip shows a "not in retrieval" warning.
 */
export default function Citation({ resourceId, data, label, onOpen }: Props) {
  const [open, setOpen] = useState(false);
  const [hovered, setHovered] = useState(false);
  const known = !!data;
  const hasReason = known && !!data.reason;

  const rawLabel = label ?? (known ? data.title : resourceId);
  const chipLabel = rawLabel.length > 42 ? rawLabel.slice(0, 40).trimEnd() + "..." : rawLabel;

  return (
    <span
      className="relative inline-block"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <button
        onClick={() => onOpen ? onOpen() : setOpen(!open)}
        className={
          "citation-chip " +
          (known ? "" : "!bg-amber-100 !text-amber-900")
        }
      >
        {chipLabel}
      </button>

      {/* Hover tooltip — shows "why this source?" reason */}
      {hovered && hasReason && !open && (
        <div className="absolute z-20 bottom-full mb-2 left-1/2 -translate-x-1/2 w-56 bg-stone-900 text-white text-[11px] leading-relaxed rounded-lg px-3 py-2 shadow-lg pointer-events-none">
          <p className="text-green-300 font-medium mb-0.5 text-[10px] uppercase tracking-wide">Why this source?</p>
          <p>{data!.reason}</p>
          <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-stone-900" />
        </div>
      )}

      {/* Click popover — shows excerpt (only when no onOpen handler) */}
      {open && (
        <div
          className="absolute z-10 left-0 top-full mt-1 w-80 bg-white border border-stone-300 rounded shadow-lg p-3 text-sm font-sans"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-baseline justify-between mb-1">
            <span className="text-xs font-mono text-green-800">{resourceId}</span>
            {known && (
              <span className="text-xs text-stone-400">page {data.page_num}</span>
            )}
            <button
              onClick={() => setOpen(false)}
              className="text-stone-400 hover:text-stone-600 text-xs"
              aria-label="Close"
            >
              ✕
            </button>
          </div>
          {known ? (
            <>
              <p className="font-medium text-stone-900 mb-2 leading-snug">{data.title}</p>
              <p className="text-stone-600 text-xs leading-relaxed italic">
                "…{data.excerpt}…"
              </p>
            </>
          ) : (
            <p className="text-amber-800 text-xs">
              This citation was generated by the model but doesn't match a retrieved passage.
              Treat with caution — could be a hallucinated reference.
            </p>
          )}
        </div>
      )}
    </span>
  );
}

// TODO (Claude Code):
// - Replace popover with a side-panel detail view that shows full metadata
// - Link to the source PDF (would require serving PDFs, e.g., from S3 or app/public/)
// - Use Headless UI / Radix Popover for proper a11y (keyboard nav, focus trap, etc.)
