"use client";

import { useState } from "react";

interface CitationData {
  resource_id: string;
  title: string;
  page_num: number;
  score: number;
  excerpt: string;
}

interface Props {
  resourceId: string;
  data?: CitationData;
  /** If provided, clicking the chip calls this instead of toggling the inline popover. */
  onOpen?: () => void;
}

/** Inline citation chip. Clicking opens a small popover with the source excerpt.
 *
 * The chip renders even if `data` is missing (e.g., the model cited an id that
 * wasn't in the retrieval set — possible if hallucinated). In that case the
 * tooltip shows a "not in retrieval" warning.
 */
export default function Citation({ resourceId, data, onOpen }: Props) {
  const [open, setOpen] = useState(false);
  const known = !!data;

  const chipLabel = known
    ? data.title.length > 38
      ? data.title.slice(0, 36).trimEnd() + "..."
      : data.title
    : resourceId;

  return (
    <span className="relative inline-block">
      <button
        onClick={() => onOpen ? onOpen() : setOpen(!open)}
        className={
          "citation-chip " +
          (known ? "" : "!bg-amber-100 !text-amber-900")
        }
        title={known ? `${data.title} (p.${data.page_num})` : "Citation not in retrieved set"}
      >
        {chipLabel}
      </button>
      {open && (
        <div
          className="absolute z-10 left-0 top-full mt-1 w-80 bg-white border border-stone-300 rounded shadow-lg p-3 text-sm font-sans"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-baseline justify-between mb-1">
            <span className="text-xs font-mono text-green-800">{resourceId}</span>
            {known && (
              <span className="text-xs text-stone-400">page {data.page_num}</span>
            )}
            <button
              onClick={() => setOpen(false)}
              className="text-stone-400 hover:text-stone-600 text-xs"
              aria-label="Close"
            >
              ✕
            </button>
          </div>
          {known ? (
            <>
              <p className="font-medium text-stone-900 mb-2 leading-snug">{data.title}</p>
              <p className="text-stone-600 text-xs leading-relaxed italic">
                "…{data.excerpt}…"
              </p>
            </>
          ) : (
            <p className="text-amber-800 text-xs">
              This citation was generated by the model but doesn't match a retrieved passage.
              Treat with caution — could be a hallucinated reference.
            </p>
          )}
        </div>
      )}
    </span>
  );
}

// TODO (Claude Code):
// - Replace popover with a side-panel detail view that shows full metadata
// - Link to the source PDF (would require serving PDFs, e.g., from S3 or app/public/)
// - Use Headless UI / Radix Popover for proper a11y (keyboard nav, focus trap, etc.)
